# Generated by Django 4.2.6 on 2023-10-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_comments_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='comment',
            new_name='comments',
        ),
    ]
