# Generated by Django 4.2.6 on 2023-10-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
