# Generated by Django 4.2.6 on 2023-10-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
    ]
