# Generated by Django 4.2.6 on 2023-10-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_news_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='authors',
        ),
        migrations.AddField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.news'),
        ),
    ]
