# Generated by Django 4.2.6 on 2023-10-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rumors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
