# Generated by Django 4.2.6 on 2023-10-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_favoritecoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecoin',
            name='coin_id',
        ),
        migrations.RemoveField(
            model_name='favoritecoin',
            name='symbol',
        ),
    ]
