# Generated by Django 4.2.3 on 2023-11-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.news'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
