# Generated by Django 4.2.3 on 2023-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_comments_news_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecoin',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
