# Generated by Django 4.2.3 on 2023-11-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_favoritecoin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecoin',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
