# Generated by Django 4.2.3 on 2023-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_favoritecoin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritecoin',
            name='price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
